const dummyData = [
  {
    created_at: "2018-03-14T03:50:30.000Z",
    title: "Stephen Hawking has died",
    url: "http://www.bbc.com/news/uk-43396008",
    author: "Cogito",
    points: 6015,
    story_text: null,
    comment_text: null,
    num_comments: 436,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1520999430,
    relevancy_score: 8012,
    _tags: ["story", "author_Cogito", "story_16582136"],
    objectID: "16582136",
    _highlightResult: {
      title: {
        value: "Stephen Hawking has died",
        matchLevel: "none",
        matchedWords: [],
      },
      url: {
        value: "http://www.bbc.com/news/uk-43396008",
        matchLevel: "none",
        matchedWords: [],
      },
      author: { value: "Cogito", matchLevel: "none", matchedWords: [] },
    },
  },
  {
    created_at: "2016-02-17T08:38:37.000Z",
    title: "A Message to Our Customers",
    url: "http://www.apple.com/customer-letter/",
    author: "epaga",
    points: 5771,
    story_text: null,
    comment_text: null,
    num_comments: 967,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1455698317,
    relevancy_score: 6561,
    _tags: ["story", "author_epaga", "story_11116274"],
    objectID: "11116274",
    _highlightResult: {
      title: {
        value: "A Message to Our Customers",
        matchLevel: "none",
        matchedWords: [],
      },
      url: {
        value: "http://www.apple.com/customer-letter/",
        matchLevel: "none",
        matchedWords: [],
      },
      author: { value: "epaga", matchLevel: "none", matchedWords: [] },
    },
  },
  {
    created_at: "2022-05-04T15:06:41.000Z",
    title: "Mechanical Watch",
    url: "https://ciechanow.ski/mechanical-watch/",
    author: "todsacerdoti",
    points: 4298,
    story_text: null,
    comment_text: null,
    num_comments: 412,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1651676801,
    _tags: ["story", "author_todsacerdoti", "story_31261533"],
    objectID: "31261533",
    _highlightResult: {
      title: {
        value: "Mechanical Watch",
        matchLevel: "none",
        matchedWords: [],
      },
      url: {
        value: "https://ciechanow.ski/mechanical-watch/",
        matchLevel: "none",
        matchedWords: [],
      },
      author: {
        value: "todsacerdoti",
        matchLevel: "none",
        matchedWords: [],
      },
    },
  },
  {
    created_at: "2011-10-05T23:42:23.000Z",
    title: "Steve Jobs has passed away.",
    url: "http://www.apple.com/stevejobs/",
    author: "patricktomas",
    points: 4271,
    story_text: "",
    comment_text: null,
    num_comments: 376,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1317858143,
    relevancy_score: 3496,
    _tags: ["story", "author_patricktomas", "story_3078128"],
    objectID: "3078128",
    _highlightResult: {
      title: {
        value: "Steve Jobs has passed away.",
        matchLevel: "none",
        matchedWords: [],
      },
      url: {
        value: "http://www.apple.com/stevejobs/",
        matchLevel: "none",
        matchedWords: [],
      },
      author: {
        value: "patricktomas",
        matchLevel: "none",
        matchedWords: [],
      },
      story_text: { value: "", matchLevel: "none", matchedWords: [] },
    },
  },
  {
    created_at: "2020-10-23T19:26:35.000Z",
    title: "YouTube-dl has received a DMCA takedown from RIAA",
    url: "https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md",
    author: "phantop",
    points: 4240,
    story_text: null,
    comment_text: null,
    num_comments: 1411,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1603481195,
    _tags: ["story", "author_phantop", "story_24872911"],
    objectID: "24872911",
    _highlightResult: {
      title: {
        value: "YouTube-dl has received a DMCA takedown from RIAA",
        matchLevel: "none",
        matchedWords: [],
      },
      url: {
        value:
          "https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md",
        matchLevel: "none",
        matchedWords: [],
      },
      author: { value: "phantop", matchLevel: "none", matchedWords: [] },
    },
  },
  {
    created_at: "2017-02-19T21:16:33.000Z",
    title: "Reflecting on one very, very strange year at Uber",
    url: "https://www.susanjfowler.com/blog/2017/2/19/reflecting-on-one-very-strange-year-at-uber",
    author: "grey-area",
    points: 4107,
    story_text: null,
    comment_text: null,
    num_comments: 1014,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1487538993,
    relevancy_score: 7260,
    _tags: ["story", "author_grey-area", "story_13682022"],
    objectID: "13682022",
    _highlightResult: {
      title: {
        value: "Reflecting on one very, very strange year at Uber",
        matchLevel: "none",
        matchedWords: [],
      },
      url: {
        value:
          "https://www.susanjfowler.com/blog/2017/2/19/reflecting-on-one-very-strange-year-at-uber",
        matchLevel: "none",
        matchedWords: [],
      },
      author: { value: "grey-area", matchLevel: "none", matchedWords: [] },
    },
  },
  {
    created_at: "2021-04-05T14:04:22.000Z",
    title: "Google’s copying of the Java SE API was fair use [pdf]",
    url: "https://www.supremecourt.gov/opinions/20pdf/18-956_d18f.pdf",
    author: "pdoconnell",
    points: 4103,
    story_text: null,
    comment_text: null,
    num_comments: 930,
    story_id: null,
    story_title: null,
    story_url: null,
    parent_id: null,
    created_at_i: 1617631462,
    _tags: ["story", "author_pdoconnell", "story_26699106"],
    objectID: "26699106",
    _highlightResult: {
      title: {
        value: "Google’s copying of the Java SE API was fair use [pdf]",
        matchLevel: "none",
        matchedWords: [],
      },
      url: {
        value: "https://www.supremecourt.gov/opinions/20pdf/18-956_d18f.pdf",
        matchLevel: "none",
        matchedWords: [],
      },
      author: { value: "pdoconnell", matchLevel: "none", matchedWords: [] },
    },
  },
];

export default dummyData;
