// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfNDAAuFTvc2OguOF2kfQJxe5O25S7aJQ',
    appId: '1:1013656648337:web:05fc55ee926972c21a5d30',
    messagingSenderId: '1013656648337',
    projectId: 'blm-app-30387',
    authDomain: 'blm-app-30387.firebaseapp.com',
    storageBucket: 'blm-app-30387.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxEecSoA7cv-fMqvYePt4i7o0vpnUya6k',
    appId: '1:1013656648337:android:b2dd7e55680175e11a5d30',
    messagingSenderId: '1013656648337',
    projectId: 'blm-app-30387',
    storageBucket: 'blm-app-30387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAGBEVkSnznd6MmOXQ5FwoSruT2cyR834',
    appId: '1:1013656648337:ios:fa94bd43b97b7e5c1a5d30',
    messagingSenderId: '1013656648337',
    projectId: 'blm-app-30387',
    storageBucket: 'blm-app-30387.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAGBEVkSnznd6MmOXQ5FwoSruT2cyR834',
    appId: '1:1013656648337:ios:763accdfb7c86aac1a5d30',
    messagingSenderId: '1013656648337',
    projectId: 'blm-app-30387',
    storageBucket: 'blm-app-30387.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfNDAAuFTvc2OguOF2kfQJxe5O25S7aJQ',
    appId: '1:1013656648337:web:1596e58f09dca5a61a5d30',
    messagingSenderId: '1013656648337',
    projectId: 'blm-app-30387',
    authDomain: 'blm-app-30387.firebaseapp.com',
    storageBucket: 'blm-app-30387.firebasestorage.app',
  );
}
