# Name of workflow
name: Linting code

# When workflow is triggered
on: push

# Jobs to carry out
jobs:
  install:
    # Operating system to run on
    runs-on: ubuntu-latest

    # Command to run
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Linting code
        run: npm run lint
